version: '3.2'

networks:
    neo4j:
        driver: bridge

services:
    client:
        build:
            context: ../
            dockerfile: docker/Dockerfile-php-8.0
            args:
                - WITH_XDEBUG=true
        networks:
            - neo4j
        depends_on:
            - neo4j
        volumes:
            - ../:/opt/project
    neo4j:
        networks:
            - neo4j
        image: neo4j:2.3
        expose:
            - 7474
            - 7687
        environment:
            - NEO4J_AUTH=neo4j/test
