name: Full Test

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: "Running full tests"
    env:
      NEO4J_CONNECTIONS: ${{ secrets.NEO4J_CONNECTIONS }}

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
        with:
          progress: yes
          php_version: 7.4
          version: 2
      - uses: php-actions/phpunit@v3
        with:
          configuration: phpunit.xml.dist
          php_version: 7.4
          php_extensions: bcmath
          memory_limit: 1024M
          bootstrap: vendor/autoload.php

    services:
      neo4j:
        image: neo4j:4.3
        env:
          NEO4J_AUTH: neo4j/test
          NEO4JLABS_PLUGINS: '["apoc"]'
        options: >-
          --health-cmd "wget http://localhost:7474 || exit 1"
          --health-interval 30s
          --health-timeout 10s
          --health-retries 5
        ports:
          - 7687:7687
          - 7474:7474

      core1:
        image: neo4j:4.3-enterprise
        env:
          NEO4J_ACCEPT_LICENSE_AGREEMENT: yes
          NEO4JLABS_PLUGINS: '["apoc"]'
          NEO4J_AUTH: neo4j/test
          NEO4J_dbms_mode: CORE
          NEO4J_causalClustering_discoveryAdvertisedAddress: core1:5000
          NEO4J_causalClustering_transactionAdvertisedAddress: core1:6000
          NEO4J_causalClustering_raftAdvertisedAddress: core1:7000
          NEO4J_causalClustering_initialDiscoveryMembers: core1:5000,core2:5000,core3:5000
          NEO4J_causal__clustering_disable__middleware__logging: false
          NEO4J_dbms_connector_bolt_advertised__address: localhost:17687
          NEO4J_dbms_connector_bolt_listen__address: 0.0.0.0:7687
          NEO4J_dbms_connector_http_advertised__address: localhost:17474
          NEO4J_dbms_connector_http_listen__address: 0.0.0.0:7474
        options: >-
          --health-cmd "wget http://localhost:7474 || exit 1"
        ports:
          - 17687:7687
          - 17474:7474
      core2:
        image: neo4j:4.3-enterprise
        env:
          NEO4J_ACCEPT_LICENSE_AGREEMENT: yes
          NEO4JLABS_PLUGINS: '["apoc"]'
          NEO4J_AUTH: neo4j/test
          NEO4J_dbms_mode: CORE
          NEO4J_causalClustering_discoveryAdvertisedAddress: core2:5000
          NEO4J_causalClustering_transactionAdvertisedAddress: core2:6000
          NEO4J_causalClustering_raftAdvertisedAddress: core2:7000
          NEO4J_causalClustering_initialDiscoveryMembers: core1:5000,core2:5000,core3:5000
          NEO4J_dbms_connector_bolt_advertised__address: localhost:27687
          NEO4J_dbms_connector_bolt_listen__address: 0.0.0.0:7687
          NEO4J_dbms_connector_http_advertised__address: localhost:27474
          NEO4J_dbms_connector_http_listen__address: 0.0.0.0:7474
        ports:
          - 27687:7687
          - 27474:7474

      core3:
        image: neo4j:4.3-enterprise
        env:
          NEO4J_ACCEPT_LICENSE_AGREEMENT: yes
          NEO4JLABS_PLUGINS: '["apoc"]'
          NEO4J_AUTH: neo4j/test
          NEO4J_dbms_mode: CORE
          NEO4J_causalClustering_discoveryAdvertisedAddress: core3:5000
          NEO4J_causalClustering_transactionAdvertisedAddress: core3:6000
          NEO4J_causalClustering_raftAdvertisedAddress: core3:7000
          NEO4J_causalClustering_initialDiscoveryMembers: core1:5000,core2:5000,core3:5000
          NEO4J_dbms_connector_bolt_advertised__address: localhost:37687
          NEO4J_dbms_connector_bolt_listen__address: 0.0.0.0:7687
          NEO4J_dbms_connector_http_advertised__address: localhost:37474
          NEO4J_dbms_connector_http_listen__address: 0.0.0.0:7474
        options: >-
          --health-cmd "wget http://localhost:7474 || exit 1"
        ports:
          - 37687:7687
          - 37474:7474

      readreplica1:
        image: neo4j:4.3-enterprise
        env:
          NEO4J_ACCEPT_LICENSE_AGREEMENT: yes
          NEO4JLABS_PLUGINS: '["apoc"]'
          NEO4J_AUTH: neo4j/test
          NEO4J_dbms_mode: READ_REPLICA
          NEO4J_causalClustering_discoveryAdvertisedAddress: readreplica1:5000
          NEO4J_causalClustering_transactionAdvertisedAddress: readreplica1:6000
          NEO4J_causalClustering_raftAdvertisedAddress: readreplica1:7000
          NEO4J_causalClustering_initialDiscoveryMembers: core1:5000,core2:5000,core3:5000
          NEO4J_dbms_connector_bolt_advertised__address: localhost:47687
          NEO4J_dbms_connector_bolt_listen__address: 0.0.0.0:7687
          NEO4J_dbms_connector_http_advertised__address: localhost:47474
          NEO4J_dbms_connector_http_listen__address: 0.0.0.0:7474
        options: >-
          --health-cmd "wget http://localhost:7474 || exit 1"
        ports:
          - 47687:7687
          - 47474:7474

