name: Full Test

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: "Running full tests"
    env:
      NEO4J_CONNECTIONS: ${{ secrets.NEO4J_CONNECTIONS }}

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
        with:
          progress: yes
          php_version: 7.4
          version: 2
      - uses: php-actions/phpunit@v3
        with:
          configuration: phpunit.xml.dist
          php_version: 7.4
          php_extensions: bcmath
          memory_limit: 1024M
          bootstrap: vendor/autoload.php

    services:
      neo4j:
        image: neo4j:4.3
        env:
          NEO4J_AUTH: neo4j/test
          NEO4JLABS_PLUGINS: '["apoc"]'
        options: >-
          --health-cmd "wget http://localhost:7474 || exit 1"
          --health-interval 30s
          --health-timeout 10s
          --health-retries 5
        ports:
          - 7687:7687
          - 7474:7474

      core1:
        image: neo4j:4.3-enterprise
        env:
          NEO4J_ACCEPT_LICENSE_AGREEMENT: yes
          NEO4JLABS_PLUGINS: '["apoc"]'
          NEO4J_AUTH: neo4j/test
          NEO4J_dbms_mode: CORE
          NEO4J_causal__clustering_discovery__advertised__address: core1:5000
          NEO4J_causal__clustering_transaction__advertised__address: core1:6000
          NEO4J_causal__clustering_raft__advertised__address: core1:7000
          NEO4J_causal__clustering_initial__discovery__members: core1:5000,core2:5000,core3:5000
          NEO4J_causal__clustering_discovery__listen__address: 0.0.0.0:5000
          NEO4J_causal__clustering_transaction__listen__address: 0.0.0.0:6000
          NEO4J_causal__clustering_raft__listen__address: 0.0.0.0:7000
          NEO4J_dbms_connector_bolt_advertised__address: localhost:17687
          NEO4J_dbms_connector_http_advertised__address: localhost:17474
        options: >-
          --health-cmd "wget http://localhost:7474 || exit 1"
        ports:
          - 17687:7687
          - 17474:7474
      core2:
        image: neo4j:4.3-enterprise
        env:
          NEO4J_ACCEPT_LICENSE_AGREEMENT: yes
          NEO4JLABS_PLUGINS: '["apoc"]'
          NEO4J_AUTH: neo4j/test
          NEO4J_dbms_mode: CORE
          NEO4J_causal__clustering_discovery__advertised__address: core2:5000
          NEO4J_causal__clustering_transaction__advertised__address: core2:6000
          NEO4J_causal__clustering_raft__advertised__address: core2:7000
          NEO4J_causal__clustering_initial__discovery__members: core1:5000,core2:5000,core3:5000
          NEO4J_causal__clustering_discovery__listen__address: 0.0.0.0:5000
          NEO4J_causal__clustering_transaction__listen__address: 0.0.0.0:6000
          NEO4J_causal__clustering_raft__listen__address: 0.0.0.0:7000
          NEO4J_dbms_connector_bolt_advertised__address: localhost:27687
          NEO4J_dbms_connector_http_advertised__address: localhost:27474
        ports:
          - 27687:7687
          - 27474:7474

      core3:
        image: neo4j:4.3-enterprise
        env:
          NEO4J_ACCEPT_LICENSE_AGREEMENT: yes
          NEO4JLABS_PLUGINS: '["apoc"]'
          NEO4J_AUTH: neo4j/test
          NEO4J_dbms_mode: CORE
          NEO4J_causal__clustering_discovery__advertised__address: core3:5000
          NEO4J_causal__clustering_transaction__advertised__address: core3:6000
          NEO4J_causal__clustering_raft__advertised__address: core3:7000
          NEO4J_causal__clustering_initial__discovery__members: core1:5000,core2:5000,core3:5000
          NEO4J_causal__clustering_discovery__listen__address: 0.0.0.0:5000
          NEO4J_causal__clustering_transaction__listen__address: 0.0.0.0:6000
          NEO4J_causal__clustering_raft__listen__address: 0.0.0.0:7000
          NEO4J_dbms_connector_bolt_advertised__address: localhost:37687
          NEO4J_dbms_connector_http_advertised__address: localhost:37474
        options: >-
          --health-cmd "wget http://localhost:7474 || exit 1"
        ports:
          - 37687:7687
          - 37474:7474

      readreplica1:
        image: neo4j:4.3-enterprise
        env:
          NEO4J_ACCEPT_LICENSE_AGREEMENT: yes
          NEO4JLABS_PLUGINS: '["apoc"]'
          NEO4J_AUTH: neo4j/test
          NEO4J_dbms_mode: READ_REPLICA
          NEO4J_causal__clustering_discovery__advertised__address: readreplica1:5000
          NEO4J_causal__clustering_transaction__advertised__address: readreplica1:6000
          NEO4J_causal__clustering_raft__advertised__address: readreplica1:7000
          NEO4J_causal__clustering_initial__discovery__members: core1:5000,core2:5000,core3:5000
          NEO4J_causal__clustering_discovery__listen__address: 0.0.0.0:5000
          NEO4J_causal__clustering_transaction__listen__address: 0.0.0.0:6000
          NEO4J_causal__clustering_raft__listen__address: 0.0.0.0:7000
          NEO4J_dbms_connector_bolt_advertised__address: localhost:47687
          NEO4J_dbms_connector_http_advertised__address: localhost:47474
        options: >-
          --health-cmd "wget http://localhost:7474 || exit 1"
        ports:
          - 47687:7687
          - 47474:7474

