name: Unit and Integration Tests

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: ['**']

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      NEO4J_CONNECTIONS: bolt://neo4j:test@neo4j,http://neo4j:test@neo4j
    name: "Running test for PHP ${{ matrix.php-version }} on Neo4j ${{ matrix.neo4j-version }} with simple config"
    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.4', '8.0', '8.1']
        neo4j-version: ["3.5", "4.0", "4.1", "4.2", "4.3"]

    services:
      neo4j:
        image: neo4j:${{ matrix.neo4j-version }}
        env:
          NEO4J_AUTH: neo4j/test
          NEO4JLABS_PLUGINS: '["apoc"]'
        options: >-
          --health-cmd "wget http://localhost:7474 || exit 1"

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
        with:
          progress: yes
          php_version: ${{ matrix.php-version }}
          version: 2
      - uses: php-actions/phpunit@v3
        with:
          configuration: phpunit.xml.dist
          php_version: ${{ matrix.php-version }}
          php_extensions: bcmath
          memory_limit: 1024M
          bootstrap: vendor/autoload.php
