name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: "Neo4j PHP Client tests"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: "Checkout branch"
        uses: actions/checkout@v2
      - name: "Pull"
        run: docker-compose -f docker/docker-compose.yml pull
      - name: "Build"
        run: |
          docker build -t php-neo4j:static-analysis . \
            && docker-compose -f docker/docker-compose.yml build --parallel \
            && docker-compose build
      - name: "Static Analysis"
        run: |
          docker run php-neo4j:static-analysis tools/php-cs-fixer/vendor/bin/php-cs-fixer fix --dry-run \
            && docker run php-neo4j:static-analysis tools/psalm/vendor/bin/psalm --show-info=true
      - name: "Test"
        run: |
          docker-compose -f docker/docker-compose.yml down --volumes --remove-orphans \
            && docker-compose -f docker/docker-compose.yml up -d --force-recreate --remove-orphans \
            && sleep 15 \
            && docker-compose -f docker/docker-compose.yml ps \
            && docker-compose -f docker/docker-compose.yml run client-80 php vendor/bin/phpunit \
            && docker-compose -f docker/docker-compose.yml run client-74 php vendor/bin/phpunit
      - name: "Coverage"
        run: |
          docker-compose -f docker/docker-compose.yml run client bash -c "\
              cc-test-reporter before-build && \
              vendor/bin/phpunit --config phpunit.coverage.xml.dist -d memory_limit=1024M && \
              cp out/phpunit/clover.xml clover.xml && \
              cc-test-reporter after-build --id ec331dd009edca126a4c27f4921c129de840c8a117643348e3b75ec547661f28 --exit-code 0"


