on: [ push, pull_request ]
name: Lint
jobs:
  php-cs-fixer:
    name: "PHP-CS-Fixer"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ '7.4', '8' ]
      fail-fast: false
    steps:
      - uses: actions/checkout@master
      - name: "PHP-CS-Fixer"
        uses: docker://oskarstark/php-cs-fixer-ga:2.19.0
        with:
          args: --dry-run
      - name: "PHPSalm"
        uses: docker://vimeo/psalm-github-actions
        with:
          composer_require_dev: true
          composer_ignore_platform_reqs: true
