name: Unit Tests

on:
  pull_request:
    branches: [ '**' ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.4', '8']
        neo4j-version: ["3.5", "4.0", "4.1", "4.2"]
    name: "Running Unit Tests for PHP ${{matrix.php-version}} on Neo4j ${{matrix.neo4j-version}}"
    services:
      neo4j:
        image: neo4j:${{matrix.neo4j-version}}
        ports:
          - 7474:7474
          - 7687:7686
        env:
          NEO4J_AUTH: neo4j/test
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{matrix.php-version}}
          extensions: gd, sockets, bcmath
      - name: Install dependencies
        uses: php-actions/composer@v5
        with:
          php_version: ${{matrix.php-version}}
          php_extensions: gd sockets bcmath
      - name: Run unit tests
        run: vendor/bin/phpunit tests/Unit

