name: Unit Tests

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.4', '8']
        neo4j-version: ["3.5", "4.0", "4.1", "4.2"]
    name: "Running Unit Tests for PHP ${php-version} on Neo4j ${neo4j-version}"
    services:
      neo4j:
        image: neo4j:${neo4j-version}
        ports:
          - 7474
          - 7687
        env:
          NEO4J_AUTH: neo4j/test
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${php-version}
      - name: Install dependencies
        uses: php-actions/composer@v5
      - name: Run unit tests
        run: vendor/bin/phpunit tests/Unit

